/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects/{projectId}/lights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクトの照明一覧を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 照明一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LightArray"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** プロジェクトの照明一覧を保存（全件置き換え） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LightInputArray"];
                };
            };
            responses: {
                /** @description 保存成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト一覧を取得（将来の共有機能向け） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description プロジェクト一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LightArray: components["schemas"]["Light"][];
        Light: components["schemas"]["LightInput"] & {
            /** @description 照明 ID */
            id: string;
            /** @description 表示順 */
            order: number;
        };
        /** @enum {string} */
        LightType: "spotlight" | "cone" | "cylinder-a" | "cylinder-b";
        /** @description 光源位置 */
        Vector3: {
            x: number;
            y: number;
            z: number;
        };
        LightInput: {
            type: components["schemas"]["LightType"];
            /**
             * @description 照明カラー（16進数整数値 例: 0xff0000 = 16711680）
             * @example 16711680
             */
            color: number;
            /**
             * @description 光の強さ（0.0〜5.0）
             * @example 2
             */
            intensity: number;
            position: components["schemas"]["Vector3"];
            targetPosition: components["schemas"]["Vector3"] & unknown;
        };
        ErrorResponse: {
            error: string;
        };
        SuccessResponse: {
            success: boolean;
        };
        LightInputArray: components["schemas"]["LightInput"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
